import { readFile, writeFile, access } from 'node:fs/promises'
import { spawnSync } from 'node:child_process'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const cli = path.join(root, 'node_modules', '@capacitor', 'cli', 'bin', 'capacitor')
const managedHeader = '// Generated by scripts/android-project.mjs; contains no signing secrets.'
const signingScript = `${managedHeader}
def signingEnvironment = [
    'ARDECHOISE_KEYSTORE_PATH',
    'ARDECHOISE_KEYSTORE_PASSWORD',
    'ARDECHOISE_KEY_ALIAS',
    'ARDECHOISE_KEY_PASSWORD'
]
def hasReleaseSigning = signingEnvironment.every { System.getenv(it) }

android {
    defaultConfig {
        if (System.getenv('ARDECHOISE_VERSION_CODE')) {
            versionCode Integer.parseInt(System.getenv('ARDECHOISE_VERSION_CODE'))
        }
        if (System.getenv('ARDECHOISE_VERSION_NAME')) {
            versionName System.getenv('ARDECHOISE_VERSION_NAME')
        }
    }
    if (hasReleaseSigning) {
        signingConfigs {
            ardechoiseRelease {
                storeFile file(System.getenv('ARDECHOISE_KEYSTORE_PATH'))
                storePassword System.getenv('ARDECHOISE_KEYSTORE_PASSWORD')
                keyAlias System.getenv('ARDECHOISE_KEY_ALIAS')
                keyPassword System.getenv('ARDECHOISE_KEY_PASSWORD')
            }
        }
        buildTypes {
            release {
                signingConfig signingConfigs.ardechoiseRelease
            }
        }
    }
}
`

async function exists(file) {
  try {
    await access(file)
    return true
  } catch {
    return false
  }
}

function capacitor(...args) {
  const result = spawnSync(process.execPath, [cli, ...args], {
    cwd: root,
    stdio: 'inherit',
    env: process.env,
  })
  if (result.error || result.status !== 0) {
    throw new Error(`Capacitor ${args.join(' ')} a échoué.`)
  }
}

async function main() {
  const [major, minor] = process.versions.node.split('.').map(Number)
  if (!((major === 20 && minor >= 19) || (major === 22 && minor >= 12) || major > 22)) {
    throw new Error('Node 20.19+ ou 22.12+ est nécessaire (Vite 7 / Capacitor 7).')
  }
  const config = JSON.parse(await readFile(path.join(root, 'capacitor.config.json'), 'utf8'))
  if (config.webDir !== 'dist-android' || config.server?.url) {
    throw new Error('Android doit embarquer le jeu local depuis dist-android, sans server.url.')
  }
  const html = await readFile(path.join(root, 'dist-android', 'index.html'), 'utf8')
  if (html.includes('/ardechoise-vite/') || html.includes('/src/main.jsx')) {
    throw new Error('Bundle Android incorrect : exécuter npm run build:android.')
  }
  const versions = await Promise.all(['cli', 'core', 'android'].map(async (name) => {
    const manifest = JSON.parse(await readFile(path.join(root, 'node_modules', '@capacitor', name, 'package.json'), 'utf8'))
    return manifest.version
  }))
  if (versions.some((version) => version.split('.')[0] !== '7')) {
    throw new Error('Les trois paquets @capacitor doivent utiliser la version majeure 7.')
  }
  if (process.argv.includes('--check')) {
    console.log('Configuration Capacitor et bundle Android valides ; aucun projet natif modifié.')
    return
  }
  if (!await exists(path.join(root, 'android'))) capacitor('add', 'android')
  const gradlePath = path.join(root, 'android', 'app', 'build.gradle')
  const managedPath = path.join(root, 'android', 'app', 'ardechoise.release.gradle')
  if (await exists(managedPath)) {
    const previous = await readFile(managedPath, 'utf8')
    if (!previous.startsWith(managedHeader)) {
      throw new Error('ardechoise.release.gradle existe déjà et contient une configuration personnelle ; vérifier avant de relancer.')
    }
  }
  await writeFile(managedPath, signingScript, 'utf8')
  const gradle = await readFile(gradlePath, 'utf8')
  const applyStatement = "apply from: 'ardechoise.release.gradle'"
  if (!gradle.includes(applyStatement)) {
    await writeFile(gradlePath, `${gradle.trimEnd()}\n\n${applyStatement}\n`, 'utf8')
  }
  capacitor('sync', 'android')
  console.log('Projet Android synchronisé. Ouvrir Android Studio avec npm run android:open.')
}

main().catch((error) => {
  console.error(error.message)
  process.exitCode = 1
})
